From home-assistant/addons

diff --git a/openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/finish b/openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/finish
--- a/openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/finish
+++ b/openthread_border_router/rootfs/etc/s6-overlay/s6-rc.d/otbr-agent/finish
@@ -51,8 +51,7 @@ bashio::log.info "OTBR firewall teardown completed."
 
 if test "$e" -ne 0; then
     echo "$e" > /run/s6-linux-init-container-results/exitcode
-    # It seems this is required otherwise this script gets called twice for some
-    # reason...
-    s6-svc -d /run/s6-rc/servicedirs/otbr-agent/
     /run/s6/basedir/bin/halt
+    # Consider any otbr-agent exit as permanent failure according to s6
+    exit 125
 fi
